export interface AppTab {
  id: string;
  clusterId?: string;
  clusterName?: string;
  environment?: 'Production' | 'Staging' | 'Development' | 'Local' | string;
  resource: string;
  title: string;
  /** Empty array means "All Namespaces" — multi-select, not a single string. */
  namespaces: string[];
  filterQuery: string;
}

export const RESOURCE_TITLES: Record<string, string> = {
  dashboard: 'Cluster Metrics',
  nodes: 'Nodes',
  events: 'Events',
  namespaces: 'Namespaces',
  mutatingwebhooks: 'Mutating Webhooks',
  validatingwebhooks: 'Validating Webhooks',
  pods: 'Pods',
  pod: 'Pods',
  po: 'Pods',
  deployments: 'Deployments',
  deployment: 'Deployments',
  deploy: 'Deployments',
  daemonsets: 'DaemonSets',
  daemonset: 'DaemonSets',
  ds: 'DaemonSets',
  statefulsets: 'StatefulSets',
  statefulset: 'StatefulSets',
  statefullsets: 'StatefulSets',
  statefullset: 'StatefulSets',
  sts: 'StatefulSets',
  replicasets: 'ReplicaSets',
  replicaset: 'ReplicaSets',
  rs: 'ReplicaSets',
  jobs: 'Jobs',
  job: 'Jobs',
  cronjobs: 'CronJobs',
  cronjob: 'CronJobs',
  cj: 'CronJobs',
  configmaps: 'ConfigMaps',
  configmap: 'ConfigMaps',
  cm: 'ConfigMaps',
  secrets: 'Secrets',
  secret: 'Secrets',
  sec: 'Secrets',
  resourcequotas: 'Resource Quotas',
  resourcequota: 'Resource Quotas',
  limitranges: 'Limit Ranges',
  limitrange: 'Limit Ranges',
  hpas: 'HPAs',
  hpa: 'HPAs',
  pdbs: 'PDBs',
  pdb: 'PDBs',
  priorityclasses: 'Priority Classes',
  priorityclass: 'Priority Classes',
  services: 'Services',
  service: 'Services',
  svc: 'Services',
  endpoints: 'Endpoints',
  endpoint: 'Endpoints',
  ep: 'Endpoints',
  ingresses: 'Ingresses',
  ingress: 'Ingresses',
  ing: 'Ingresses',
  ingressclasses: 'Ingress Classes',
  ingressclass: 'Ingress Classes',
  networkpolicies: 'Network Policies',
  networkpolicy: 'Network Policies',
  pvcs: 'Persistent Volume Claims',
  pvc: 'Persistent Volume Claims',
  pvs: 'Persistent Volumes',
  pv: 'Persistent Volumes',
  storageclasses: 'Storage Classes',
  storageclass: 'Storage Classes',
  serviceaccounts: 'Service Accounts',
  serviceaccount: 'Service Accounts',
  sa: 'Service Accounts',
  clusterroles: 'Cluster Roles',
  clusterrole: 'Cluster Roles',
  cr: 'Cluster Roles',
  clusterrolebindings: 'Cluster Role Bindings',
  clusterrolebinding: 'Cluster Role Bindings',
  crb: 'Cluster Role Bindings',
  roles: 'Roles',
  role: 'Roles',
  ro: 'Roles',
  rolebindings: 'Role Bindings',
  rolebinding: 'Role Bindings',
  rb: 'Role Bindings',
  crds: 'Definitions',
  crd: 'Definitions',
  'helm-releases': 'Helm Releases',
  helm: 'Helm Releases',
};
